# WHAT IS PYTORCH?

It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- a deep learning research platform that provides maximum flexibility and speed

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Random 5x3 matrix

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0767, 0.3882, 0.3357],
        [0.0472, 0.0596, 0.9491],
        [0.3545, 0.4779, 0.4379],
        [0.9051, 0.5578, 0.4288],
        [0.2847, 0.0851, 0.8322]])


5x3 matrix filled with 0s of type long

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


A tensor directly from the data

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Create a tensor based on existing tensors

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0173,  0.5488,  1.5863],
        [-1.8878, -1.7626, -2.1645],
        [ 1.1982, -1.1805, -0.1600],
        [-0.2186, -0.5086,  0.4005],
        [-0.9720, -0.4769, -0.8642]])


Get a size

In [8]:
print(x.size())

torch.Size([5, 3])


Operations

In [9]:
# addition
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.1102,  1.0383,  1.5951],
        [-1.8619, -1.6047, -2.0260],
        [ 1.3713, -0.2501,  0.6569],
        [ 0.4363, -0.2797,  1.3219],
        [-0.9334, -0.3640, -0.3897]])


In [10]:
# alternative way to add
print(torch.add(x, y))

tensor([[ 0.1102,  1.0383,  1.5951],
        [-1.8619, -1.6047, -2.0260],
        [ 1.3713, -0.2501,  0.6569],
        [ 0.4363, -0.2797,  1.3219],
        [-0.9334, -0.3640, -0.3897]])


In [11]:
# output as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.1102,  1.0383,  1.5951],
        [-1.8619, -1.6047, -2.0260],
        [ 1.3713, -0.2501,  0.6569],
        [ 0.4363, -0.2797,  1.3219],
        [-0.9334, -0.3640, -0.3897]])


In [12]:
# in place addition
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.1102,  1.0383,  1.5951],
        [-1.8619, -1.6047, -2.0260],
        [ 1.3713, -0.2501,  0.6569],
        [ 0.4363, -0.2797,  1.3219],
        [-0.9334, -0.3640, -0.3897]])


In [13]:
# resizing a tensor
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# getting one element
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1388])
-0.13882139325141907


In [15]:
# converting a torch tensor to a numpy array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


remember to use _ for in place editing

In [18]:
# converting numpy array to torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Moving tensor to CUDA

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!